import type {
  DashboardArtifact,
  ReplayLiveState,
  SandboxLiveState,
} from "@paybench/contracts";
import type { CanonicalRunRecords } from "./repository";

const emptyStudy = {
  target: 10,
  valid: 0,
  a_valid: 0,
  b_valid: 0,
  flagged: 0,
  rejected: 0,
  technical_failures: 0,
};

const queuedReplay: ReplayLiveState = {
  status: "queued",
  completed_checks: 0,
  total_checks: 8,
  blocking_findings: 0,
};

const readySandboxes: SandboxLiveState[] = [
  {
    variant: "A",
    sandbox_id: "demo-sandbox-a",
    status: "ready",
    task: "Control paywall ready",
    last_activity_at: "2026-08-15T20:12:00.000Z",
  },
  {
    variant: "B",
    sandbox_id: "demo-sandbox-b",
    status: "ready",
    task: "Challenger paywall ready",
    last_activity_at: "2026-08-15T20:13:00.000Z",
  },
];

const variantArtifacts: DashboardArtifact[] = [
  {
    kind: "variant_a",
    label: "Control preview",
    object_path: "jobs/demo-active/variants/a/index.html",
    created_at: "2026-08-15T20:12:00.000Z",
  },
  {
    kind: "variant_b",
    label: "Challenger preview",
    object_path: "jobs/demo-active/variants/b/index.html",
    created_at: "2026-08-15T20:13:00.000Z",
  },
];

export const DEMO_CANONICAL_RUNS: readonly CanonicalRunRecords[] = [
  {
    job: {
      id: "7c59d21a-9ef0-45f3-8958-b8b20f1d84c0",
      founder_label: "Northstar",
      website_url: "https://northstar.example/pricing",
      status: "testing",
      source: "demo",
      next_action_code: "WAIT_FOR_STUDY",
      updated_at: "2026-08-15T20:24:00.000Z",
    },
    payments: [{ status: "succeeded", amount_cents: 2000, currency: "USD" }],
    stage_progress: [
      { stage: "intake", status: "complete" },
      { stage: "payment", status: "complete" },
      { stage: "capture", status: "complete" },
      { stage: "variants", status: "complete" },
      { stage: "replay", status: "complete" },
      { stage: "study", status: "running" },
    ],
    sandboxes: readySandboxes,
    study: {
      target: 10,
      valid: 0,
      a_valid: 0,
      b_valid: 0,
      flagged: 0,
      rejected: 0,
      technical_failures: 0,
    },
    replay: {
      status: "passed",
      current_journey: "All journeys passed",
      completed_checks: 8,
      total_checks: 8,
      blocking_findings: 0,
      last_activity_at: "2026-08-15T20:15:00.000Z",
    },
    artifacts: variantArtifacts,
    transitions: [
      {
        event_id: "529bd797-a562-45ca-9ea6-d3f07a6f9d97",
        stage: "intake",
        status: "complete",
        actor: "paybench",
        summary_code: "intake_received",
        occurred_at: "2026-08-15T20:00:00.000Z",
      },
      {
        event_id: "0d2d13f2-06ac-4c03-be5d-dcc3ed7edaf2",
        stage: "payment",
        status: "complete",
        actor: "stripe",
        summary_code: "payment_confirmed",
        occurred_at: "2026-08-15T20:03:00.000Z",
      },
      {
        event_id: "cfc0c8ae-a89e-43d3-a094-e48330cb94d7",
        stage: "capture",
        status: "running",
        actor: "superserve",
        summary_code: "capture_started",
        occurred_at: "2026-08-15T20:04:00.000Z",
      },
      {
        event_id: "657492a4-aa36-4a02-8d9d-1ff84e5d3ddd",
        stage: "variants",
        status: "complete",
        actor: "superserve",
        summary_code: "variants_ready",
        occurred_at: "2026-08-15T20:14:00.000Z",
      },
      {
        event_id: "d840ec8e-5592-4852-8aa6-03fc7794fd29",
        stage: "study",
        status: "running",
        actor: "terac",
        summary_code: "study_started",
        occurred_at: "2026-08-15T20:16:00.000Z",
      },
      {
        event_id: "7e46042d-eeaa-4d74-9c88-27ac287d98e0",
        stage: "study",
        status: "running",
        actor: "terac",
        summary_code: "study_progress",
        occurred_at: "2026-08-15T20:24:00.000Z",
      },
    ],
  },
  {
    job: {
      id: "03a16b13-9ee4-4d4c-a40b-8b8b133fdcc1",
      founder_label: "Cedar",
      website_url: "https://cedar.example/plans",
      status: "needs_scout",
      source: "demo",
      blocker_code: "SCOUT_REQUIRED",
      next_action_code: "POST_SCOUT_TASK",
      updated_at: "2026-08-15T19:42:00.000Z",
    },
    payments: [{ status: "succeeded", amount_cents: 2000, currency: "USD" }],
    stage_progress: [
      { stage: "intake", status: "complete" },
      { stage: "payment", status: "complete" },
      { stage: "capture", status: "blocked" },
    ],
    sandboxes: [],
    study: emptyStudy,
    replay: queuedReplay,
    artifacts: [],
    transitions: [
      {
        event_id: "01e343c3-6232-43a6-b235-28253ca2a643",
        stage: "intake",
        status: "complete",
        actor: "paybench",
        summary_code: "intake_received",
        occurred_at: "2026-08-15T19:30:00.000Z",
      },
      {
        event_id: "b4b57234-275d-4df7-82c0-eb4e7c845d48",
        stage: "payment",
        status: "complete",
        actor: "stripe",
        summary_code: "payment_confirmed",
        occurred_at: "2026-08-15T19:33:00.000Z",
      },
      {
        event_id: "916b9b31-de84-45df-aedf-27ddefc4569f",
        stage: "capture",
        status: "running",
        actor: "superserve",
        summary_code: "capture_started",
        occurred_at: "2026-08-15T19:34:00.000Z",
      },
      {
        event_id: "3caecdf9-725e-43bd-b027-7c77e4828da6",
        stage: "capture",
        status: "blocked",
        actor: "superserve",
        summary_code: "capture_blocked",
        occurred_at: "2026-08-15T19:41:00.000Z",
      },
      {
        event_id: "20c042f2-2265-4f2f-8518-c0de7322172b",
        stage: "capture",
        status: "blocked",
        actor: "terac",
        summary_code: "scout_requested",
        occurred_at: "2026-08-15T19:42:00.000Z",
      },
    ],
  },
  {
    job: {
      id: "7c874f29-1b85-4f68-8280-f696af881ae1",
      founder_label: "Orbit",
      website_url: "https://orbit.example/upgrade",
      status: "failed",
      source: "demo",
      failed_stage: "replay",
      blocker_code: "REPLAY_BLOCKED",
      next_action_code: "FIX_REPLAY_FINDING",
      updated_at: "2026-08-15T18:58:00.000Z",
    },
    payments: [{ status: "succeeded", amount_cents: 2000, currency: "USD" }],
    stage_progress: [
      { stage: "intake", status: "complete" },
      { stage: "payment", status: "complete" },
      { stage: "capture", status: "complete" },
      { stage: "variants", status: "complete" },
      { stage: "replay", status: "failed" },
      { stage: "study", status: "waiting" },
    ],
    sandboxes: readySandboxes.map((sandbox) => ({
      ...sandbox,
      sandbox_id: sandbox.variant === "A" ? "demo-orbit-a" : "demo-orbit-b",
    })),
    study: {
      target: 10,
      valid: 0,
      a_valid: 0,
      b_valid: 0,
      flagged: 0,
      rejected: 2,
      technical_failures: 1,
    },
    replay: {
      status: "failed",
      current_journey: "Complete simulated purchase",
      completed_checks: 7,
      total_checks: 8,
      blocking_findings: 1,
      run_url: "https://app.replay.io/recording/paybench-demo-replay-failed",
      last_activity_at: "2026-08-15T18:58:00.000Z",
    },
    artifacts: variantArtifacts.map((artifact) => ({
      ...artifact,
      object_path: artifact.object_path.replace("demo-active", "demo-replay-failed"),
    })),
    transitions: [
      {
        event_id: "15c9ef9a-981d-4305-9517-8f0729965207",
        stage: "payment",
        status: "complete",
        actor: "stripe",
        summary_code: "payment_confirmed",
        occurred_at: "2026-08-15T18:20:00.000Z",
      },
      {
        event_id: "d1d4f79d-ac66-41b4-890d-23cf77417bed",
        stage: "variants",
        status: "complete",
        actor: "superserve",
        summary_code: "variants_ready",
        occurred_at: "2026-08-15T18:36:00.000Z",
      },
      {
        event_id: "8e2ff2da-f27a-42e4-986f-97b83bdf0840",
        stage: "replay",
        status: "running",
        actor: "replay",
        summary_code: "replay_started",
        occurred_at: "2026-08-15T18:54:00.000Z",
      },
      {
        event_id: "e334def0-a054-4a94-a8b7-bc471bb9f259",
        stage: "replay",
        status: "failed",
        actor: "replay",
        summary_code: "replay_failed",
        occurred_at: "2026-08-15T18:58:00.000Z",
      },
    ],
  },
] as const;
